### ISSUE TITLE
Data Request screen

### ISSUE THREAD

**Issue by mdfrederick** [Masterworks/Clarity-Components#17]
Before they select a job - https://projects.invisionapp.com/share/UJJCGK5E6NX#/screens/298844081
After they select a job - https://projects.invisionapp.com/share/UJJCGK5E6NX#/screens/298844082
Ready to submit modal - https://projects.invisionapp.com/share/UJJCGK5E6NX#/screens/304386120
Completed and with a Comments section - https://projects.invisionapp.com/share/UJJCGK5E6NX#/screens/298844080

@Chitradip-Capitalnumbers The completed and with comments section might be something you haven't looked at, please take note of the Comments. We'll be building those soon, don't miss them!

**Comment by Chitradip-Capitalnumbers** [comment]
@mdfrederick  Somehow I have missed that comment section. Actually in figma file that section was not present that the main reason I have missed that. But I have updated that now as per invision. Also, completed the "After they select a job" page. Please check both files.

Thanks!

**Comment by mdfrederick** [comment]
@danielgolden When you get a chance, can you review this one, and close if it's all good. Thank you.

**Comment by danielgolden** [comment]
@Chitradip-Capitalnumbers Thank you for your work on this page, however there are _many_ issues related to the details of the design of this page. Again, please use direct measurements and specifications from Figma. I am going to list several issues below, please check to see if any of these problems exist in the component and/or in the ui guide so that these issues do not persist in the future. Here are the issues:

### Secondary Header Section
- The "Enter Project Title" text is the wrong color.
- The dashed underline of the "Enter Project Title" does not have the proper spacing and size for and between the dashes.
- The vertical borders between sections should be dotted, not dashed.
- The color and font-family of the tag are incorrect.
- The tag is not centered between the borders on either side of it.
- The "filter codes" text should be set in semi-bold

### Body
- The labels of the text inputs should not revert to lowercase when they lose focus.
- The `letter-spacing: 6%` style being applied to the table header labels is not working. If the letter-spacing property does not accept percent values, you can just use 1px.
- The code descriptions are set in the wrong color.

### Comments
- All tags are set in the wrong font and they may also have the wrong padding (please check the padding).
- If you look closely at the design in Figma, you can see that there is [a small gap between each comment container and the timeline itself](https://user-images.githubusercontent.com/812989/43326050-cab2b09e-9185-11e8-9d97-d7bd87d0f9e2.png). Please measure this gap and implement it.
- There is too much spacing around each individual comment header and comment body ([here is a screenshot](https://user-images.githubusercontent.com/812989/43326501-07cb94f4-9187-11e8-82a1-c400dca64841.png) that specifies the spacing that I'm talking about). Please measure and apply the proper spacing from Figma.
- The comment textarea placeholder text and actual value text are set in the wrong font and have the wrong color.

---

I'm am available on Slack and or Zoom if you have _any_ questions at all, or if you're unsure about any of these points of feedback please let me know and I'll be glad to clarify.

All of the above issues are based on differences between the design in Figma and the design of the page you've built. In the future, please check your work against what is in Figma very closely. The details of these designs are important.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden 
I have fixed all these issues.
Please check and let me know your concern.

Thanks!

**Comment by danielgolden** [comment]
#### The following issues have not been fixed:
- The font of the "Enter Project Title" is the wrong font (mentioned yesterday during our call) .
- The options for small select elements are set in the wrong font (mentioned a while ago on another page and issue)
- The comment placeholder text has been corrected, but the actual text when typed in is still the wrong color. Should be set in #273A4B.
- The margins on `.c-comments__list--block p` are still not correct. They're closer, but not correct. If it will be easier you can just give them 12px padding on top and on bottom. That will be sufficient.

#### The following issues are new:
- All select element labels are set in all caps when unfocused. This should not be.

#### This one I just didn't notice before:
- The background color for `.c-comments__box ul li.c-comments__list--complete:before` is the wrong color.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden 
I have fixed those issue please check and let me know your concern.

Thanks!

**Comment by danielgolden** [comment]
### The following issues have still not been resolved:
- The options for small select elements are set in the wrong font (mentioned a while ago on another page and issue). [This is the wrong font](https://user-images.githubusercontent.com/812989/43522893-b1f09f80-9568-11e8-9bad-08b2ef78e1c3.png).
- The comment textarea text is the wrong font.
- [This select label should not be set in all caps by default](https://user-images.githubusercontent.com/812989/43523134-62987268-9569-11e8-97a6-282cae7446c9.png). Please use figma as a reference for the designs of all of these pages.

### New Issues
- [Select labels should not have any letter-spacing when they don't have focus](https://user-images.githubusercontent.com/812989/43523222-b5ada11c-9569-11e8-91e3-fa81767d2202.png).
